baseURL = '/'
languageCode = 'en-us'
title = 'Sun Sea Sangria'
theme = 'paige'
copyright = '© 2025 Sun Sea Sangria. All rights reserved.'

[taxonomies]
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Welcome to Sun Sea Sangria"

[params.paige.site]
  disable_breadcrumbs = true
  disable_credit = true

[params.social]
  facebook = "https://www.facebook.com/profile.php?id=61587601735754"
  instagram = "https://www.instagram.com/sunseasangriablog/"
  x = "https://x.com/Sunseasangria25"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[menu.main]]
  name = "About Me"
  url = "/about-me/"
  weight = 30

[[menu.main]]
  name = "Contact"
  url = "/contact-me/"
  weight = 40

